### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by basnijholt** [craigbarratt/hass-pyscript-jupyter#3]
When starting a notebook:
```python
(py38) basnijholt-imac  ➜  Downloads  jupyter-notebook Untitled.ipynb --debug
[D 18:44:38.116 NotebookApp] Searching ['/Users/basnijholt/Downloads', '/Users/basnijholt/.jupyter', '/Users/basnijholt/miniconda3/envs/py38/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 18:44:38.117 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 18:44:38.117 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 18:44:38.117 NotebookApp] Looking for jupyter_config in /Users/basnijholt/miniconda3/envs/py38/etc/jupyter
[D 18:44:38.117 NotebookApp] Looking for jupyter_config in /Users/basnijholt/.jupyter
[D 18:44:38.117 NotebookApp] Looking for jupyter_config in /Users/basnijholt/Downloads
[D 18:44:38.118 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 18:44:38.118 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 18:44:38.118 NotebookApp] Looking for jupyter_notebook_config in /Users/basnijholt/miniconda3/envs/py38/etc/jupyter
[D 18:44:38.118 NotebookApp] Looking for jupyter_notebook_config in /Users/basnijholt/.jupyter
[D 18:44:38.119 NotebookApp] Loaded config file: /Users/basnijholt/.jupyter/jupyter_notebook_config.json
[D 18:44:38.119 NotebookApp] Looking for jupyter_notebook_config in /Users/basnijholt/Downloads
[D 18:44:38.120 NotebookApp] Raising open file limit: soft 256->4096; hard 9223372036854775807->9223372036854775807
[D 18:44:38.123 NotebookApp] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 18:44:38.124 NotebookApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 18:44:38.124 NotebookApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/jupyter_notebook_config.d/ipyparallel-serverextension.json
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/jupyter_notebook_config.json
[D 18:44:38.125 NotebookApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/basnijholt/.jupyter/jupyter_notebook_config.json
[I 18:44:38.382 NotebookApp] Loading IPython parallel extension
[D 18:44:38.401 NotebookApp] [jupyter_nbextensions_configurator] Loading 0.4.1
[D 18:44:38.402 NotebookApp] [jupyter_nbextensions_configurator]   Editing templates path to add /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/jupyter_nbextensions_configurator/templates
[D 18:44:38.402 NotebookApp] [jupyter_nbextensions_configurator]   Editing nbextensions path to add /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/jupyter_nbextensions_configurator/static
[D 18:44:38.402 NotebookApp] [jupyter_nbextensions_configurator]   Adding new handlers
[I 18:44:38.402 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 18:44:38.402 NotebookApp] Serving notebooks from local directory: /Users/basnijholt/Downloads
[I 18:44:38.402 NotebookApp] Jupyter Notebook 6.1.3 is running at:
[I 18:44:38.402 NotebookApp] http://localhost:8888/?token=fd8b9eb8f8fb0bea2d10e5e4809f8e88d9381677ca8a7a18
[I 18:44:38.402 NotebookApp]  or http://127.0.0.1:8888/?token=fd8b9eb8f8fb0bea2d10e5e4809f8e88d9381677ca8a7a18
[I 18:44:38.402 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:44:38.489 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///Users/basnijholt/Library/Jupyter/runtime/nbserver-20823-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=fd8b9eb8f8fb0bea2d10e5e4809f8e88d9381677ca8a7a18
     or http://127.0.0.1:8888/?token=fd8b9eb8f8fb0bea2d10e5e4809f8e88d9381677ca8a7a18
[D 18:44:39.764 NotebookApp] Accepting token-authenticated connection from ::1
[D 18:44:39.767 NotebookApp] Using contents: services/contents
[D 18:44:39.847 NotebookApp] Path base/images/favicon-notebook.ico served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/base/images/favicon-notebook.ico
[D 18:44:39.847 NotebookApp] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css
[D 18:44:39.849 NotebookApp] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/jquery-typeahead/dist/jquery.typeahead.min.css
[D 18:44:39.849 NotebookApp] Path components/bootstrap-tour/build/css/bootstrap-tour.min.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/bootstrap-tour/build/css/bootstrap-tour.min.css
[D 18:44:39.851 NotebookApp] Path components/codemirror/lib/codemirror.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/codemirror/lib/codemirror.css
[D 18:44:39.852 NotebookApp] Path style/style.min.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/style/style.min.css
[D 18:44:39.853 NotebookApp] Path notebook/css/override.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/notebook/css/override.css
[D 18:44:39.853 NotebookApp] Path components/es6-promise/promise.min.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/es6-promise/promise.min.js
[D 18:44:39.854 NotebookApp] Path components/react/react.production.min.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/react/react.production.min.js
[D 18:44:39.854 NotebookApp] Path components/react/react-dom.production.min.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/react/react-dom.production.min.js
[D 18:44:39.854 NotebookApp] Path components/create-react-class/index.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/create-react-class/index.js
[D 18:44:39.855 NotebookApp] Path components/requirejs/require.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/requirejs/require.js
[D 18:44:39.855 NotebookApp] Path base/images/logo.png served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/base/images/logo.png
[D 18:44:40.012 NotebookApp] Paths used for configuration of notebook:
    	/etc/jupyter/nbconfig/notebook.json
[D 18:44:40.012 NotebookApp] Paths used for configuration of notebook:
    	/usr/local/etc/jupyter/nbconfig/notebook.json
[D 18:44:40.013 NotebookApp] Paths used for configuration of notebook:
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/nbconfig/notebook.d/widgetsnbextension.json
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/nbconfig/notebook.json
[D 18:44:40.013 NotebookApp] Paths used for configuration of notebook:
    	/Users/basnijholt/.jupyter/nbconfig/notebook.json
[D 18:44:40.274 NotebookApp] Path components/text-encoding/lib/encoding.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/text-encoding/lib/encoding.js
[D 18:44:40.274 NotebookApp] Path notebook/js/main.min.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/notebook/js/main.min.js
[D 18:44:40.286 NotebookApp] 200 GET /notebooks/Untitled.ipynb?token=fd8b9eb8f8fb0bea2d10e5e4809f8e88d9381677ca8a7a18 (::1) 521.67ms
[D 18:44:40.292 NotebookApp] Initializing websocket connection /api/kernels/b17056c9-11a4-41a2-be78-2a415de096d8/channels
[W 18:44:40.337 NotebookApp] 404 GET /api/kernels/b17056c9-11a4-41a2-be78-2a415de096d8/channels?session_id=d78d3fd55a224a2380c44523ffbda5f9 (::1): Kernel does not exist: b17056c9-11a4-41a2-be78-2a415de096d8
[D 18:44:40.338 NotebookApp] Using contents: services/contents
[D 18:44:40.369 NotebookApp] Path base/images/favicon.ico served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/base/images/favicon.ico
[W 18:44:40.378 NotebookApp] 404 GET /api/kernels/b17056c9-11a4-41a2-be78-2a415de096d8/channels?session_id=d78d3fd55a224a2380c44523ffbda5f9 (::1) 86.62ms referer=None
[D 18:44:40.380 NotebookApp] Path components/MathJax/MathJax.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/MathJax.js
[D 18:44:40.381 NotebookApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&delayStartupUntil=configured (::1) 1.77ms
[D 18:44:40.404 NotebookApp] Path custom.css served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/custom/custom.css
[D 18:44:40.405 NotebookApp] 304 GET /custom/custom.css (::1) 1.69ms
[D 18:44:40.475 NotebookApp] Path components/MathJax/config/TeX-AMS-MML_HTMLorMML-full.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/config/TeX-AMS-MML_HTMLorMML-full.js
[D 18:44:40.476 NotebookApp] 304 GET /static/components/MathJax/config/TeX-AMS-MML_HTMLorMML-full.js?V=2.7.8 (::1) 1.02ms
[D 18:44:40.587 NotebookApp] Path services/contents.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/services/contents.js
[D 18:44:40.589 NotebookApp] 200 GET /static/services/contents.js?v=20200828184438 (::1) 3.10ms
[D 18:44:40.659 NotebookApp] Path components/MathJax/config/Safe.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/config/Safe.js
[D 18:44:40.660 NotebookApp] 304 GET /static/components/MathJax/config/Safe.js?V=2.7.8 (::1) 0.97ms
[D 18:44:40.674 NotebookApp] Paths used for configuration of notebook:
    	/etc/jupyter/nbconfig/notebook.json
[D 18:44:40.674 NotebookApp] Paths used for configuration of notebook:
    	/usr/local/etc/jupyter/nbconfig/notebook.json
[D 18:44:40.675 NotebookApp] Paths used for configuration of notebook:
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/nbconfig/notebook.d/widgetsnbextension.json
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/nbconfig/notebook.json
[D 18:44:40.676 NotebookApp] Paths used for configuration of notebook:
    	/Users/basnijholt/.jupyter/nbconfig/notebook.json
[D 18:44:40.676 NotebookApp] 200 GET /api/config/notebook?_=1598633080534 (::1) 3.93ms
[D 18:44:40.677 NotebookApp] Paths used for configuration of common:
    	/etc/jupyter/nbconfig/common.json
[D 18:44:40.678 NotebookApp] Paths used for configuration of common:
    	/usr/local/etc/jupyter/nbconfig/common.json
[D 18:44:40.678 NotebookApp] Paths used for configuration of common:
    	/Users/basnijholt/miniconda3/envs/py38/etc/jupyter/nbconfig/common.json
[D 18:44:40.679 NotebookApp] Paths used for configuration of common:
    	/Users/basnijholt/.jupyter/nbconfig/common.json
[D 18:44:40.679 NotebookApp] 200 GET /api/config/common?_=1598633080535 (::1) 6.39ms
[D 18:44:40.720 NotebookApp] Found kernel python3 in /Users/basnijholt/miniconda3/envs/py38/share/jupyter/kernels
[D 18:44:40.720 NotebookApp] Found kernel pyscript in /Users/basnijholt/miniconda3/envs/py38/share/jupyter/kernels
[D 18:44:40.724 NotebookApp] 304 GET /api/kernelspecs (::1) 4.53ms
[D 18:44:40.822 NotebookApp] 200 GET /api/contents/Untitled.ipynb?type=notebook&_=1598633080536 (::1) 10.29ms
[D 18:44:40.824 NotebookApp] Path custom.js served from /Users/basnijholt/.jupyter/custom/custom.js
[D 18:44:40.824 NotebookApp] 200 GET /custom/custom.js?v=20200828184438 (::1) 1.19ms
[D 18:44:41.023 NotebookApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?_=1598633080537 (::1) 2.00ms
[D 18:44:41.301 NotebookApp] Path jupyter-js-widgets/extension.js served from /Users/basnijholt/miniconda3/envs/py38/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
[D 18:44:41.303 NotebookApp] Path jupyter-black-master/jupyter-black.js served from /Users/basnijholt/Library/Jupyter/nbextensions/jupyter-black-master/jupyter-black.js
[D 18:44:41.304 NotebookApp] 200 GET /nbextensions/jupyter-black-master/jupyter-black.js?v=20200828184438 (::1) 1.29ms
[D 18:44:41.308 NotebookApp] Path nbextensions_configurator/config_menu/main.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/jupyter_nbextensions_configurator/static/nbextensions_configurator/config_menu/main.js
[D 18:44:41.309 NotebookApp] 200 GET /nbextensions/nbextensions_configurator/config_menu/main.js?v=20200828184438 (::1) 2.07ms
[D 18:44:41.309 NotebookApp] Path contrib_nbextensions_help_item/main.js served from /Users/basnijholt/Library/Jupyter/nbextensions/contrib_nbextensions_help_item/main.js
[D 18:44:41.310 NotebookApp] 200 GET /nbextensions/contrib_nbextensions_help_item/main.js?v=20200828184438 (::1) 2.57ms
[D 18:44:41.311 NotebookApp] Path code_prettify/isort.js served from /Users/basnijholt/Library/Jupyter/nbextensions/code_prettify/isort.js
[D 18:44:41.312 NotebookApp] 200 GET /nbextensions/code_prettify/isort.js?v=20200828184438 (::1) 1.71ms
[D 18:44:41.313 NotebookApp] 200 GET /nbextensions/jupyter-js-widgets/extension.js?v=20200828184438 (::1) 13.26ms
[D 18:44:41.333 NotebookApp] Path components/MathJax/extensions/TeX/newcommand.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/extensions/TeX/newcommand.js
[D 18:44:41.333 NotebookApp] 304 GET /static/components/MathJax/extensions/TeX/newcommand.js?V=2.7.8 (::1) 1.05ms
[D 18:44:41.335 NotebookApp] Path components/MathJax/extensions/TeX/begingroup.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/extensions/TeX/begingroup.js
[D 18:44:41.335 NotebookApp] 304 GET /static/components/MathJax/extensions/TeX/begingroup.js?V=2.7.8 (::1) 1.35ms
[D 18:44:41.336 NotebookApp] Path components/MathJax/extensions/MathML/content-mathml.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/extensions/MathML/content-mathml.js
[D 18:44:41.336 NotebookApp] 304 GET /static/components/MathJax/extensions/MathML/content-mathml.js?V=2.7.8 (::1) 1.53ms
[D 18:44:41.388 NotebookApp] Starting kernel: ['/Users/basnijholt/miniconda3/envs/py38/bin/python', '/Users/basnijholt/miniconda3/envs/py38/share/jupyter/kernels/pyscript/hass_pyscript_kernel.py', '/Users/basnijholt/Library/Jupyter/runtime/kernel-7b5f6d54-ac0c-4211-bf97-8b34583e7005.json']
[D 18:44:41.396 NotebookApp] Connecting to: tcp://127.0.0.1:50087
[D 18:44:41.397 NotebookApp] Connecting to: tcp://127.0.0.1:50085
[I 18:44:41.399 NotebookApp] Kernel started: 7b5f6d54-ac0c-4211-bf97-8b34583e7005, name: pyscript
[D 18:44:41.399 NotebookApp] Kernel args: {'kernel_name': 'pyscript', 'cwd': '/Users/basnijholt/Downloads'}
[D 18:44:41.400 NotebookApp] 201 POST /api/sessions (::1) 57.15ms
[D 18:44:41.402 NotebookApp] Path components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js
[D 18:44:41.402 NotebookApp] 304 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js?V=2.7.8 (::1) 1.35ms
[D 18:44:41.440 NotebookApp] Path components/MathJax/extensions/Safe.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/MathJax/extensions/Safe.js
[D 18:44:41.441 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?V=2.7.8 (::1) 2.52ms
[D 18:44:41.484 NotebookApp] Initializing websocket connection /api/kernels/7b5f6d54-ac0c-4211-bf97-8b34583e7005/channels
[D 18:44:41.486 NotebookApp] Requesting kernel info from 7b5f6d54-ac0c-4211-bf97-8b34583e7005
[D 18:44:41.486 NotebookApp] Connecting to: tcp://127.0.0.1:50084
[D 18:44:41.522 NotebookApp] Path jupyter-black-master/kernel_exec_on_cell.js served from /Users/basnijholt/Library/Jupyter/nbextensions/jupyter-black-master/kernel_exec_on_cell.js
[D 18:44:41.523 NotebookApp] 200 GET /nbextensions/jupyter-black-master/kernel_exec_on_cell.js?v=20200828184438 (::1) 2.33ms
[D 18:44:41.529 NotebookApp] Path code_prettify/kernel_exec_on_cell.js served from /Users/basnijholt/Library/Jupyter/nbextensions/code_prettify/kernel_exec_on_cell.js
[D 18:44:41.530 NotebookApp] 200 GET /nbextensions/code_prettify/kernel_exec_on_cell.js?v=20200828184438 (::1) 1.70ms
[D 18:44:41.536 NotebookApp] Path components/codemirror/keymap/sublime.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/codemirror/keymap/sublime.js
[D 18:44:41.537 NotebookApp] 200 GET /static/components/codemirror/keymap/sublime.js?v=20200828184438 (::1) 1.16ms
yo
[D 18:44:41.712 NotebookApp] Path components/codemirror/addon/search/searchcursor.js served from /Users/basnijholt/miniconda3/envs/py38/lib/python3.8/site-packages/notebook/static/components/codemirror/addon/search/searchcursor.js
[D 18:44:41.713 NotebookApp] 200 GET /static/components/codemirror/addon/search/searchcursor.js?v=20200828184438 (::1) 1.85ms
[D 18:44:45.216 NotebookApp] Initializing websocket connection /api/kernels/b17056c9-11a4-41a2-be78-2a415de096d8/channels
[W 18:44:45.217 NotebookApp] Replacing stale connection: b17056c9-11a4-41a2-be78-2a415de096d8:d78d3fd55a224a2380c44523ffbda5f9
```

I added here https://github.com/craigbarratt/hass-pyscript-jupyter/blob/ffa85afeb07d13ea90228320371f459b3e3a67a3/hass_pyscript_kernel.py#L172-L180
```python
            while True:
                try:
                    kernel_reader, kernel_writer = await asyncio.open_connection(
                        self.ip_host, self.kernel_port
                    )
                    break
                except Exception as e:  # pylint: disable=broad-except
                    print(e)  # <-------------------------------------------- this
                    await asyncio.sleep(0.25)
```
and then I get many of these exceptions printed (10s every second) when I start the notebook:
```
[Errno 61] Connect call failed ('127.0.0.1', 56459)
[Errno 61] Connect call failed ('127.0.0.1', 56461)
[Errno 61] Connect call failed ('127.0.0.1', 56460)
[Errno 61] Connect call failed ('127.0.0.1', 56459)
[Errno 61] Connect call failed ('127.0.0.1', 56460)
[Errno 61] Connect call failed ('127.0.0.1', 56461)
[Errno 61] Connect call failed ('127.0.0.1', 56459)
```

**Comment by craigbarratt** [comment]
Are you running the master version of pyscript in HASS?  The released 0.11 version doesn't support Jupyter.

**Comment by basnijholt** [comment]
I am indeed using the master version of pyscript.

**Comment by craigbarratt** [comment]
No I'm not.  I can make an account...

**Comment by basnijholt** [comment]
You can find me as `basnijholt#1282`.

**Comment by craigbarratt** [comment]
Thanks for connecting on discord and thanks for the debugging help.  As we concluded, due to an embarrassing oversight, the existing code doesn't support the case that 99.9% of people use where HASS is running on a different host than Jupyter.  I just committed some [changes to pyscript](https://github.com/custom-components/pyscript/commit/2957aed8c70e762cff9b1dee9f1c9f2bcb8d3e4f) and this module (c5f6820) that should allow connections to a remote HASS instance, and while it works on localhost, I haven't tested the remote host case yet (will do so tomorrow).

`hass_pyscript_kernel.py` now has a setting for the HASS host name or IP.  I also added a `-v` command-line option to `hass_pyscript_kernel.py` that prints basic debugging information, and `-vvv` shows each connection being established.  Add those flags to `kernel.json`.  That should help debugging.

Since the connection handshake has changed, you'll need to upgrade to the latest master pyscript and `hass_pyscript_kernel.py`.

I also started a wiki on [debugging connection problems](https://github.com/craigbarratt/hass-pyscript-jupyter/wiki/Connection-problems).

**Comment by alistairg** [comment]
Unless I've missed an update of something somewhere - this is still an issue. My own hacking concluded that the service call to HASS to start the listen service for the Jupyter server tells it to listen on "127.0.0.1", which is the IP the client gets from my jupyter config.

As a result, the network connection fails to my local IP (172.16.0.2) as the server isn't listening on its LAN interface. If I hack the start service request in the kernel with the right IP - everything works great....

**Comment by craigbarratt** [comment]
Yes, that is a bug.  I just pushed a [commit to pyscript](https://github.com/custom-components/pyscript/commit/77ca1a5babdd17ccdd2394e7b745ec4d6620d7df) to use 0.0.0.0 for asyncio.start_server(); otherwise as you correctly point out it's only listening on the loopback interface when it used the ip field from the Jupyter client.

Can you confirm using the latest pyscript master works for you now?

**Comment by alistairg** [comment]
That solved it :)

**Comment by basnijholt** [comment]
Great, it now works for me too!

Note that you might have to disable some `jupyter_nbextensions`, for me the isort extension made the connection not work.
